run:
  timeout: 3m
  tests: true

linters-settings:
  gofmt:
    simplify: true

linters:
  enable:
    - bodyclose
    - errcheck
    - gocritic
    - goimports
    - gosimple
    - gosec
    - govet
    - ineffassign
    - staticcheck
    - stylecheck
    - unconvert
    - unparam
    - unused
  disable-all: true

issues:
  exclude-use-default: true
  max-issues-per-linter: 0
  max-same-issue: 0
